apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.APP_ID}}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: helm
    repoURL: https://github.com/bgpworks/devops-toolkit.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: 925081097270.dkr.ecr.us-east-1.amazonaws.com/devops-toolkit
          tag: {{.IMAGE_TAG}}
        ingress:
          host: {{.APP_ID}}.bgp.works
      version: v3
  destination:
    namespace: "{{.APP_ID}}"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
